{{- if .Values.perf.integration -}}
  {{- if .Values.perf.luminate.enabled -}}
apiVersion: v1
data:
  apiUrl: {{ .Values.perf.luminate.apiUrl }}
  credentialName: {{ .Values.perf.luminate.credentialName }}
kind: ConfigMap
metadata:
  name: luminatesec-conf
  {{end}}
{{end}}
