{{- if .Values.perf.integration -}}
apiVersion: v2.edp.epam.com/v1
kind: PerfServer
metadata:
  labels:
    {{- include "perf-operator.labels" . | nindent 4 }}
  name: {{.Values.perf.name}}
spec:
  apiUrl: {{.Values.perf.apiUrl}}
  rootUrl: {{.Values.perf.rootUrl}}
  credentialName: {{.Values.perf.credentialName}}
  projectName: {{.Values.perf.projectName}}
{{end}}
