apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: perfdatasourcegitlabs.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: PerfDataSourceGitLab
    listKind: PerfDataSourceGitLabList
    plural: perfdatasourcegitlabs
    singular: perfdatasourcegitlab
    shortNames:
      - pdsgl
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
                  of an object. Servers should convert recognized schemas to the latest
                  internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
                  object represents. Servers may infer this from the endpoint the client
                  submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            perfServerName:
              type: string
            codebaseName:
              type: string
            type:
              type: string
            name:
              type: string
            config:
              properties:
                repositories:
                  type: array
                url:
                  type: string
                branches:
                  type: array
              required:
                - repositories
                - url
                - branches
          required:
            - perfServerName
            - codebaseName
            - type
            - name
            - config
          type: object