# permissions for end users to view perfdatasourcegitlabs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: perfdatasourcegitlab-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: empty-operator
    app.kubernetes.io/part-of: empty-operator
    app.kubernetes.io/managed-by: kustomize
  name: perfdatasourcegitlab-viewer-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - perfdatasourcegitlabs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - perfdatasourcegitlabs/status
  verbs:
  - get
