apiVersion: v2.edp.epam.com/v1alpha1
kind: PerfServer
metadata:
  name: epam-perf
spec:
  apiUrl: https://perf.delivery.epam.com
  rootUrl: https://perf.delivery.epam.com
  credentialName: epam-perf-user
  projectName: epmd-edp