apiVersion: v2
description: A Helm chart for EDP Perf Operator
home: https://epam.github.io/edp-install/
name: perf-operator
type: application
version: 2.14.0-SNAPSHOT
appVersion: 2.14.0-SNAPSHOT
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - edp
  - performance
  - board
  - operator
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-perf-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: perf-operator:2.13.0
      image: epamedp/perf-operator:2.13.0
    - name: alpine:3.16.4
      image: alpine:3.16.4
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: PerfDataSourceGitLab
      version: v2.edp.epam.com/v1
      name: perfdatasourcegitlab
      displayName: PerfDataSourceGitLab
      description: Performance board configuration for GitLab
    - kind: PerfDataSourceJenkins
      version: v2.edp.epam.com/v1
      name: perfdatasourcejenkins
      displayName: PerfDataSourceJenkins
      description: Performance board configuration with Jenkins
    - kind: PerfDataSourceSonar
      version: v2.edp.epam.com/v1
      name: perfdatasourcesonar
      displayName: PerfDataSourceSonar
      description: Performance board configuration with Sonar
    - kind: PerfServer
      version: v2.edp.epam.com/v1
      name: perfserver
      displayName: PerfServer
      description: Performance board server
  artifacthub.io/crdsExamples: |
    - apiVersion: v2.edp.epam.com/v1
      kind: PerfServer
      metadata:
        name: perfserver
      spec:
        apiUrl: https://test.com/perf
        credentialName: perf-user
        projectName: MYPROJ-EDP
        rootUrl: https://test.com/unit/2074/delivery/summary
  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
