global:
  edpName: ""
  platform: "openshift"

name: perf-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  repository: epamedp/perf-operator
  # if not defined then .Chart.AppVersion is used
  tag:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

perf:
  integration: false
  name: "perf"
  apiUrl: "https://perf.delivery.example.com"
  rootUrl: "https://perf.delivery.example.com"
  credentialName: "perf-user"
  projectName: "PROJECT-NAME"
  luminate:
    enabled: false
    apiUrl: "https://api.example.luminatesec.com"
    credentialName: "luminate-secret"
