global:
  edpName: ""
  platform: "openshift"

name: perf-operator
image:
  name: epamedp/perf-operator
  version: v2.6.0

resources:
  limits:
    cpu: 200m
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

perf:
  integration: true
  name: "epam-perf"
  apiUrl: "https://perf.delivery.epam.com"
  rootUrl: "https://perf.delivery.epam.com"
  credentialName: "epam-perf-user"
  projectName: "EPMD-EDP"
  luminate:
    enabled: true
    apiUrl: "https://api.epam.luminatesec.com"
    credentialName: "luminate-secret"
