global:
  edpName: ""
  platform: "openshift"

name: perf-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  name: epamedp/perf-operator
  # if not defined then .Chart.AppVersion is used
  version:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

perf:
  integration: true
  name: "epam-perf"
  apiUrl: "https://perf.delivery.epam.com"
  rootUrl: "https://perf.delivery.epam.com"
  credentialName: "epam-perf-user"
  projectName: "EPMD-EDP"
  luminate:
    enabled: true
    apiUrl: "https://api.epam.luminatesec.com"
    credentialName: "luminate-secret"
