global:
  edpName: ""
  platform: "openshift"

name: perf-operator
image:
  name: epamedp/perf-operator
  version: v2.6.0

perf:
  integration: true
  luminate:
    enabled: true
    apiUrl: "https://api.epam.luminatesec.com"
    secretName: "luminate-secret"
  name: "epam-perf"
  apiUrl: "https://perf.delivery.epam.com"
  rootUrl: "https://perf.delivery.epam.com"
  credentialName: "epam-perf-user"
  projectName: "EPMD-EDP"