{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "perf-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
rules:
  - apiGroups:
      - '*'
    attributeRestrictions: null
    resources:
      - perfservers
      - perfservers/status
      - perfservers/finalizers
      - perfdatasourcejenkinses
      - perfdatasourcejenkinses/finalizers
      - perfdatasourcejenkinses/status
      - perfdatasourcesonars
      - perfdatasourcesonars/finalizers
      - perfdatasourcesonars/status
      - edpcomponents
      - edpcomponents/finalizers
      - edpcomponents/status
      - codebases
      - codebases/finalizers
      - codebases/status
      - perfdatasourcegitlabs
      - perfdatasourcegitlabs/finalizers
      - perfdatasourcegitlabs/status
    verbs:
      - '*'
{{ end }}
