{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Role for perf-operator-edp service account
    openshift.io/reconcile-protect: "false"
  name: {{ .Values.name }}-{{ .Values.global.edpName }}-clusterrole
rules:
  - apiGroups:
      - '*'
    attributeRestrictions: null
    resources:
      - perfservers
      - perfservers/status
      - perfservers/finalizers
      - perfdatasourcejenkinses
      - perfdatasourcejenkinses/finalizers
      - perfdatasourcejenkinses/status
      - perfdatasourcesonars
      - perfdatasourcesonars/finalizers
      - perfdatasourcesonars/status
      - edpcomponents
      - edpcomponents/finalizers
      - edpcomponents/status
    verbs:
      - '*'
{{ end }}
