{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Role for perf-operator-edp service account
    openshift.io/reconcile-protect: "false"
  name: {{ .Values.name }}-{{ .Values.global.edpName }}-clusterrole
rules:
  - apiGroups:
      - '*'
    attributeRestrictions: null
    resources:
      - perfservers
      - perfservers/status
      - perfservers/finalizers
      - perfdatasources
      - perfdatasources/status
      - perfdatasources/finalizers
      - edpcomponents
      - edpcomponents/finalizers
      - edpcomponents/status
    verbs:
      - '*'
{{ end }}
