//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	"github.com/go-openapi/spec"
	"k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/edp/v1alpha1.PerfServer":                  schema_pkg_apis_edp_v1alpha1_PerfServer(ref),
		"./pkg/apis/edp/v1alpha1.PerfServerSpec":              schema_pkg_apis_edp_v1alpha1_PerfServerSpec(ref),
		"./pkg/apis/edp/v1alpha1.PerfServerStatus":            schema_pkg_apis_edp_v1alpha1_PerfStatus(ref),
		"./pkg/apis/edp/v1alpha1.PerfDataSourceJenkins":       schema_pkg_apis_edp_v1alpha1_PerfDataSourceJenkins(ref),
		"./pkg/apis/edp/v1alpha1.PerfDataSourceJenkinsSpec":   schema_pkg_apis_edp_v1alpha1_PerfDataSourceJenkinsSpec(ref),
		"./pkg/apis/edp/v1alpha1.PerfDataSourceJenkinsStatus": schema_pkg_apis_edp_v1alpha1_PerfDataSourceJenkinsStatus(ref),
		"./pkg/apis/edp/v1alpha1.PerfDataSourceSonar":         schema_pkg_apis_edp_v1alpha1_PerfDataSourceSonar(ref),
		"./pkg/apis/edp/v1alpha1.PerfDataSourceSonarSpec":     schema_pkg_apis_edp_v1alpha1_PerfDataSourceSonarSpec(ref),
		"./pkg/apis/edp/v1alpha1.PerfDataSourceSonarStatus":   schema_pkg_apis_edp_v1alpha1_PerfDataSourceSonarStatus(ref),
		"./pkg/apis/edp/v1alpha1.PerfDataSourceGitLab":        schema_pkg_apis_edp_v1alpha1_PerfDataSourceGitLab(ref),
		"./pkg/apis/edp/v1alpha1.PerfDataSourceGitLabSpec":    schema_pkg_apis_edp_v1alpha1_PerfDataSourceGitLabSpec(ref),
		"./pkg/apis/edp/v1alpha1.PerfDataSourceGitLabStatus":  schema_pkg_apis_edp_v1alpha1_PerfDataSourceGitLabStatus(ref),
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfServer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfServer is the Schema for the perfservers API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/edp/v1alpha1.PerfServerSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/edp/v1alpha1.PerfServerStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/edp/v1alpha1.PerfServerSpec", "./pkg/apis/edp/v1alpha1.PerfServerStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfServerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfServerSpec defines the desired state of PerfServer",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"apiUrl": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"rootUrl": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"credentialName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"projectName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"apiUrl", "rootUrl", "credentialName", "projectName"},
			},
		},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfStatus defines the observed state of PerfStream",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfDataSourceJenkins(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfDataSourceJenkins is the Schema for the perfdatasourcejenkinses API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/edp/v1alpha1.PerfDataSourceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/edp/v1alpha1.PerfDataSourceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/edp/v1alpha1.PerfDataSourceJenkinsSpec", "./pkg/apis/edp/v1alpha1.PerfDataSourceJenkinsStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfDataSourceJenkinsSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfDataSourceJenkinsSpec defines the desired state of PerfDataSourceJenkins",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"perfServerName": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"type": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"config": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"object"},
							Format: "",
						},
					},
				},
				Required: []string{"perfServerName", "type", "name", "config"},
			},
		},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfDataSourceJenkinsStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfDataSourceJenkinsStatus defines the observed state of PerfDataSourceJenkinsStream",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfDataSourceSonar(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfDataSourceSonar is the Schema for the perfdatasourcesonars API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/edp/v1alpha1.PerfDataSourceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/edp/v1alpha1.PerfDataSourceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/edp/v1alpha1.PerfDataSourceSonarSpec", "./pkg/apis/edp/v1alpha1.PerfDataSourceSonarStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfDataSourceSonarSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfDataSourceSonarSpec defines the desired state of PerfDataSourceSonar",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"perfServerName": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"type": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"config": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"object"},
							Format: "",
						},
					},
				},
				Required: []string{"perfServerName", "type", "name", "config"},
			},
		},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfDataSourceSonarStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfDataSourceSonarStatus defines the observed state of PerfDataSourceSonarStream",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfDataSourceGitLab(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfDataSourceGitLab is the Schema for the perfdatasourcegitlabs API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/edp/v1alpha1.PerfDataSourceGitLabSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/edp/v1alpha1.PerfDataSourceGitLabStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/edp/v1alpha1.PerfDataSourceGitLabSpec", "./pkg/apis/edp/v1alpha1.PerfDataSourceGitLabStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfDataSourceGitLabSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfDataSourceGitLabSpec defines the desired state of PerfDataSourceGitLab",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"perfServerName": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"type": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"config": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"object"},
							Format: "",
						},
					},
				},
				Required: []string{"perfServerName", "type", "name", "config"},
			},
		},
	}
}

func schema_pkg_apis_edp_v1alpha1_PerfDataSourceGitLabStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PerfDataSourceGitLabStatus defines the observed state of PerfDataSourceGitLabStream",
				Type:        []string{"object"},
			},
		},
	}
}
