// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfServer) DeepCopyInto(out *PerfServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfServer.
func (in *PerfServer) DeepCopy() *PerfServer {
	if in == nil {
		return nil
	}
	out := new(PerfServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerfServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfServerList) DeepCopyInto(out *PerfServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PerfServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfServerList.
func (in *PerfServerList) DeepCopy() *PerfServerList {
	if in == nil {
		return nil
	}
	out := new(PerfServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerfServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfServerSpec) DeepCopyInto(out *PerfServerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfServerSpec.
func (in *PerfServerSpec) DeepCopy() *PerfServerSpec {
	if in == nil {
		return nil
	}
	out := new(PerfServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfServerStatus) DeepCopyInto(out *PerfServerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfServerStatus.
func (in *PerfServerStatus) DeepCopy() *PerfServerStatus {
	if in == nil {
		return nil
	}
	out := new(PerfServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfDataSourceJenkins) DeepCopyInto(out *PerfDataSourceJenkins) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfDataSourceJenkins.
func (in *PerfDataSourceJenkins) DeepCopy() *PerfDataSourceJenkins {
	if in == nil {
		return nil
	}
	out := new(PerfDataSourceJenkins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerfDataSourceJenkins) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfDataSourceJenkinsList) DeepCopyInto(out *PerfDataSourceJenkinsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PerfDataSourceJenkins, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfDataSourceJenkinsList.
func (in *PerfDataSourceJenkinsList) DeepCopy() *PerfDataSourceJenkinsList {
	if in == nil {
		return nil
	}
	out := new(PerfDataSourceJenkinsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerfDataSourceJenkinsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfDataSourceJenkinsSpec) DeepCopyInto(out *PerfDataSourceJenkinsSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfDataSourceJenkinsSpec.
func (in *PerfDataSourceJenkinsSpec) DeepCopy() *PerfDataSourceJenkinsSpec {
	if in == nil {
		return nil
	}
	out := new(PerfDataSourceJenkinsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfDataSourceJenkinsStatus) DeepCopyInto(out *PerfDataSourceJenkinsStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfDataSourceJenkinsStatus.
func (in *PerfDataSourceJenkinsStatus) DeepCopy() *PerfDataSourceJenkinsStatus {
	if in == nil {
		return nil
	}
	out := new(PerfDataSourceJenkinsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfDataSourceSonar) DeepCopyInto(out *PerfDataSourceSonar) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfDataSourceSonar.
func (in *PerfDataSourceSonar) DeepCopy() *PerfDataSourceSonar {
	if in == nil {
		return nil
	}
	out := new(PerfDataSourceSonar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerfDataSourceSonar) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfDataSourceSonarList) DeepCopyInto(out *PerfDataSourceSonarList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PerfDataSourceSonar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfDataSourceList.
func (in *PerfDataSourceSonarList) DeepCopy() *PerfDataSourceSonarList {
	if in == nil {
		return nil
	}
	out := new(PerfDataSourceSonarList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerfDataSourceSonarList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfDataSourceSonarSpec) DeepCopyInto(out *PerfDataSourceSonarSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfDataSourceSonarSpec.
func (in *PerfDataSourceSonarSpec) DeepCopy() *PerfDataSourceSonarSpec {
	if in == nil {
		return nil
	}
	out := new(PerfDataSourceSonarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfDataSourceSonarStatus) DeepCopyInto(out *PerfDataSourceSonarStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfDataSourceSonarStatus.
func (in *PerfDataSourceSonarStatus) DeepCopy() *PerfDataSourceSonarStatus {
	if in == nil {
		return nil
	}
	out := new(PerfDataSourceSonarStatus)
	in.DeepCopyInto(out)
	return out
}
