@startuml

skinparam class {
    BackgroundColor #white
	BackgroundColor<<wip>> LightGoldenRodYellow
	BackgroundColor<<tbd>> Khaki
}

package perf-operator {
    class PerfServer {
        -- spec --
        String apiUrl
        String rootUrl
        String credentialName
        String projectName
        -- status --
        Boolean available
        String detailedMessage
        Time lastTimeUpdated
    }

    PerfServerSecret "1" *-l- "1" PerfServer : secret
    class PerfServerSecret <Secret> {
        -- data --
        String username
        String password
    }

    LuminateSecret "1" *-l- "1" PerfServer : secret
    class LuminateSecret <Secret> {
        -- data --
        String username
        String password
    }

    class PerfDataSourceJenkins {
        -- spec --
        String name
        String type
        DataSourceConfig config
        String perfServerName
        -- status --
        String status
    }

    class PerfDataSourceSonar {
        -- spec --
        String name
        String type
        DataSourceConfig config
        String perfServerName
        -- status --
        String status
    }

    class PerfDataSourceGitLab {
        -- spec --
        String name
        String type
        DataSourceConfig config
        String perfServerName
        -- status --
        String status
    }

    PerfDataSourceJenkins "1" *-l- "1" DataSourceJenkinsConfig : internal structure
    class DataSourceJenkinsConfig {
      []String jobNames
      String url
    }

    PerfDataSourceSonar "1" *-l- "1" DataSourceSonarConfig : internal structure
    class DataSourceSonarConfig {
      []String projectKeys
      String url
    }

    PerfDataSourceGitLab "1" *-l- "1" DataSourceGitLabConfig : internal structure
    class DataSourceGitLabConfig {
      []String repositories
      []String branches
      String url
    }
}

EdpComponent <-- PerfServer : creates, owns

legend
|<back:LightGoldenRodYellow>    </back>| Work In Progress |
|<back:White>    </back>| Implemented |
|<back:Khaki>    </back>| TBD |
endlegend

@enduml