@startuml
start
:PerfDataSource CR;
:Put PerfServer Owner to CR;
:Check for the Data Source in PERF;
if (Data Source Exists) then (yes)
    if (Is Data Source Activated?) then (yes)
        :Update Data Source Entity in PERF;
    else (no)
        :Activate Data Source Entity in PERF;
        :Update Data Source Entity in PERF;
    endif
else (no)
    :Create Data Source Entity in PERF;
endif
:Update Status;
stop

legend
|= |= Component |
|<back:#lightyellow>   </back>| Perf data source |
endlegend
@enduml